language: php

php:
  - 5.6
  - 7
  - hhvm

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - bin/phpunit --coverage-clover clover.xml

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "7" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "7" ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi;'

